theme: jekyll-theme-minimal
title: Welcome to my WIP basic personal website
description: I hope to eventually add more features and details to this. If you have a suggestion, send me feedback at the usual places.
